# Generated by Django 4.2.3 on 2023-07-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anagrafica', '0002_alter_pagamento_id_contratto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='id_Contratto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratto', to='Anagrafica.contratto'),
        ),
    ]
