# Generated by Django 4.2.3 on 2023-07-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anagrafica', '0003_alter_pagamento_id_contratto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clienteCodF',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteCognome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clientepiva',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clienteregione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
