# Generated by Django 4.2.3 on 2023-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anagrafica', '0004_alter_cliente_clientecodf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratto',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
