# Generated by Django 4.2.3 on 2023-07-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anagrafica', '0005_alter_contratto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='Anagrafica.cliente'),
        ),
        migrations.AlterField(
            model_name='contratto',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contratto',
            name='importo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratto',
            name='scadenzaContratto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
